# coding=utf-8
'''
Problem 2
        Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

# 生成一个最大值不大于4百万的斐波那契数列列表
# 初始化一个列表用于存储斐波那契数列
fibo_li = [1, 2]
x, y = 1, 2
while fibo_li[-1] <= 4000000:
    tmp = x
    x = y
    y = y + tmp
    fibo_li.append(y)
# print(fibo_li)
# 初始化 n 用来存储最后的结果
n = 0
for i in fibo_li:
    if i % 2 == 0:
        n += i
print(n)
